### ISSUE TITLE
机器学习中为什么矩阵计算效率高？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#101]
- 问题链接：https://www.shiyanlou.com/questions/108344
- 学员昵称：书山压力大EE
- 提问时间：2019-04-24T13:38:29.000Z

---

机器学习中  有一个 向量化的概念，  就是为了用矩阵运算  代替  for循环，  从而极大的提高效率。

但是 这内部使用了什么数据结构和算法而从提高运算效率？ 我一直不明白， 有没有知道的大神？

我做过测试， 像numpy中矩阵相乘   比  你用for循环来实现  就快了非常多

**Comment by songyer** [comment]
已回答
