### ISSUE TITLE
代码没看懂

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#102]
- 问题链接：https://www.shiyanlou.com/questions/108349
- 学员昵称：astri
- 提问时间：2019-04-24T15:35:27.000Z

---

w0 = w_calculator(x, y)[0]
w1 = w_calculator(x, y)[1]

请问这里自定义函数[]中的[0]，[1]是什么意思？

**Comment by songyer** [comment]
已回答
