### ISSUE TITLE
针对机器学习第一周的课程提问

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#103]
- 问题链接：https://www.shiyanlou.com/questions/108565
- 学员昵称：有梦想是好事
- 提问时间：2019-04-27T12:54:28.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid971600-20190427-1556369525687)![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid971600-20190427-1556369547877)

如图所示，首先为什么要强调矩阵为满秩呢，是否因为满秩矩阵存在逆矩阵？
第二个问题就是，加截距系数1？这个地方没有搞明白，麻烦老师解惑。

**Comment by songyer** [comment]
已回答
