### ISSUE TITLE
对fit_intercept=False 的疑问

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#105]
- 问题链接：https://www.shiyanlou.com/questions/108581
- 学员昵称：书山压力大EE
- 提问时间：2019-04-28T00:56:26.000Z

---

两个问题:
1. 公式法计算得到的W  是不是  截距+系数？  如果是的话, 后面的coef不是表示系数吗？怎么会和公式法得到的W(截距+系数)结果会一致？
2.我原本对fit_intercept=False这个参数的理解是  后面intercept截距不计算了, 对系数coef应该没影响的。
但发现不是这么回事， 我希望能和我讲解下原因

对比一下下面两张图,  加不加fit_intercept=False 结果不一样
![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190428-1556412460281)
---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190428-1556412700008)

**Comment by songyer** [comment]
已回答
