### ISSUE TITLE
error: Result from function call is not a proper array of floats.

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#107]
- 问题链接：https://www.shiyanlou.com/questions/108586
- 学员昵称：Frank2009
- 提问时间：2019-04-28T02:13:27.000Z

---

n_poly(3)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: object too deep for desired array

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-124-8cd88ea80593> in <module>()
----> 1 n_poly(3)

<ipython-input-31-6d69961d6590> in n_poly(n)
     17     """
     18     p_init = np.random.randn(n)  # 生成 n 个随机数
---> 19     parameters = leastsq(err_func, p_init, args=(np.array(x), np.array(y)))
     20     return parameters[0]

/opt/conda/lib/python3.6/site-packages/scipy/optimize/minpack.py in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
    392         with _MINPACK_LOCK:
    393             retval = _minpack._lmdif(func, x0, args, full_output, ftol, xtol,
--> 394                                      gtol, maxfev, epsfcn, factor, diag)
    395     else:
    396         if col_deriv:

error: Result from function call is not a proper array of floats.

**Comment by songyer** [comment]
已回答
