### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#108]
- 问题链接：https://www.shiyanlou.com/questions/108585
- 学员昵称：Frank2009
- 提问时间：2019-04-28T02:12:28.000Z

---

def fit_func(p, x):
    f = np.poly1d(p)
    retrun f(x)
    
def err_func(p, x, y):
    ret = fit_func(p, x) - y
    return ret

def n_poly(n):
    p_init = np.random.randn(n)
    parameters = leastsq(err_func, p_init, args=(np.array(x), np.array(y)))
    return parameters[0]

  File "<ipython-input-123-cda60ab62cd2>", line 3
    retrun f(x)
           ^
SyntaxError: invalid syntax

**Comment by songyer** [comment]
已回答
