### ISSUE TITLE
数学式子推演过程没看懂

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#109]
- 问题链接：https://www.shiyanlou.com/questions/108606
- 学员昵称：书山压力大EE
- 提问时间：2019-04-28T05:51:27.000Z

---

2开头的那一项 怎么就没了？
![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190428-1556430576663)

**Comment by songyer** [comment]
已回答
