### ISSUE TITLE
对偶化dual , 有什么作用？  什么时候会用到？   希望可以尽量通俗易懂地讲解一下

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#112]
- 问题链接：https://www.shiyanlou.com/questions/108817
- 学员昵称：书山压力大EE
- 提问时间：2019-04-30T07:25:28.000Z

---

<pre style="font-size:14px; line-height:17px;" class="hljs">
LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', verbose=0, warm_start=False, n_jobs=1)
</pre>
介绍其中几个常用的参数，其余使用默认即可：
- `penalty`: 惩罚项，默认为 $L_{2}$ 范数。
- `dual`: 对偶化，默认为 False。
- `tol`: 数据解算精度。
- `fit_intercept`: 默认为 True，计算截距项。
- `random_state`: 随机数发生器。
- `max_iter`: 最大迭代次数，默认为 100。

**Comment by songyer** [comment]
已回答
