### ISSUE TITLE
学习率设置

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#113]
- 问题链接：https://www.shiyanlou.com/questions/108839
- 学员昵称：harvey14
- 提问时间：2019-04-30T11:53:29.000Z

---

这里不用设置学习率吗？好像也没有关于学习率的参数
```
 LogisticRegression(tol=0.001, max_iter=10000, solver='liblinear')
```

**Comment by songyer** [comment]
已回答
