### ISSUE TITLE
极大似然估计  的公式  每个字母都是什么意思？  能不能详细表述一下， 就以给的data为例

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#114]
- 问题链接：https://www.shiyanlou.com/questions/164471
- 学员昵称：书山压力大EE
- 提问时间：2019-05-07T14:19:35.000Z

---

$$
P(y_{i}=c_{k})=\frac{\sum_{i=1}^{N}I(y_{i}=c_{k})}{N},k=1,2,3,…,m \tag{6}
$$

**Comment by songyer** [comment]
已回答
