### ISSUE TITLE
Gain不是越大， 数据越乱分类越不确定吗？   这里划线的部分为什么要取Gain最大值作为划分点？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#119]
- 问题链接：https://www.shiyanlou.com/questions/165412
- 学员昵称：书山压力大EE
- 提问时间：2019-05-14T01:53:26.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190514-1557798685745)

**Comment by songyer** [comment]
已回答
