### ISSUE TITLE
调用RandomizedSearchCV时，使用scipy.stats.randint  就可以，   用numpy.random.randint   就报错，  为什么？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#120]
- 问题链接：https://www.shiyanlou.com/questions/165528
- 学员昵称：书山压力大EE
- 提问时间：2019-05-14T07:36:28.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190514-1557819267809)

**Comment by songyer** [comment]
已回答
