### ISSUE TITLE
装袋算法的表述不是很清楚啊？ 没有后面随机森林的表述那么清楚

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#121]
- 问题链接：https://www.shiyanlou.com/questions/165541
- 学员昵称：书山压力大EE
- 提问时间：2019-05-14T08:34:27.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190514-1557822476466)

问题：
1.     装袋算法  的取样   是有放回的取样吗？
2.     表述中T的意思：  是不是     最后有T个样本集，并且 每个样本集有T个样本数?
3.     假设现在有多个个体训练器， 是不是   每个个体训练器  都要用 所有的T个样本集数据进行训练？ 还是只用T个样本集中的一个样本集进行训练？

**Comment by songyer** [comment]
已回答
