### ISSUE TITLE
这里举出的类,  有几个不认识，也没接触过。  能不能帮我把相应的算法名字标注上？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#122]
- 问题链接：https://www.shiyanlou.com/questions/165569
- 学员昵称：书山压力大EE
- 提问时间：2019-05-15T03:47:26.000Z

---

- 分类算法
    - `sklearn.naive_bayes.MultinomialNB`
    - `sklearn.naive_bayes.BernoulliNB`
    - `sklearn.linear_model.Perceptron`
    - `sklearn.linear_model.SGDClassifier`
    - `sklearn.linear_model.PassiveAggressiveClassifier`
    - `sklearn.neural_network.MLPClassifier`

- 回归算法
    - `sklearn.linear_model.SGDRegressor`
    - `sklearn.linear_model.PassiveAggressiveRegressor`
    - `sklearn.neural_network.MLPRegressor`

**Comment by songyer** [comment]
已回答
