### ISSUE TITLE
np.linalg.eig函数返回

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#125]
- 问题链接：https://www.shiyanlou.com/questions/166092
- 学员昵称：harvey14
- 提问时间：2019-05-19T08:24:35.000Z

---

```
eigValInd = np.argsort(-eigVal)  # 特征值降序排序
bestVec = eigVec[:, eigValInd[:4]]  # 取最好的 4 个特征向量
bestVec
```

eigVal,eigVec = np.linalg.eig(np.mat(covMat))
这个函数好像返回的是已经根据特征值大小排过序（降序）的结果吧？
最上面三行应该可以直接写成：bestVec = eigVec[:,:4]   吧？

**Comment by songyer** [comment]
已回答
