### ISSUE TITLE
rowvar这参数  干嘛用的？   为什么前面调用np.cov的时候没设为False

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#129]
- 问题链接：https://www.shiyanlou.com/questions/167043
- 学员昵称：书山压力大EE
- 提问时间：2019-05-23T03:47:29.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190523-1558583200788)

**Comment by songyer** [comment]
已回答
