### ISSUE TITLE
这里的正则化， 是什么意思？有什么作用？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#130]
- 问题链接：https://www.shiyanlou.com/questions/167536
- 学员昵称：书山压力大EE
- 提问时间：2019-05-26T08:07:30.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190526-1558857985317)

**Comment by songyer** [comment]
已回答
