### ISSUE TITLE
梯度优化器为什么要清零？    就算要清零 不也应该放在 for循环开始前吗？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#131]
- 问题链接：https://www.shiyanlou.com/questions/168575
- 学员昵称：书山压力大EE
- 提问时间：2019-06-02T02:56:28.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190602-1559444067586)

**Comment by songyer** [comment]
已回答
