### ISSUE TITLE
梯度累计 到底是什么意思？  能不能那个简单例子具体说明一下？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#132]
- 问题链接：https://www.shiyanlou.com/questions/168576
- 学员昵称：书山压力大EE
- 提问时间：2019-06-02T03:01:31.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190602-1559444484396)

**Comment by songyer** [comment]
已回答
