### ISSUE TITLE
这里np.pad为什么这么写？   28x28x1的矩阵padding成32x32x1的矩阵， np.pad的参数怎么对应的？

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#133]
- 问题链接：https://www.shiyanlou.com/questions/168739
- 学员昵称：书山压力大EE
- 提问时间：2019-06-03T09:22:27.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid373872-20190603-1559553669118)

**Comment by songyer** [comment]
已回答
