### ISSUE TITLE
老师，能否给出偏导的求导过程

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#135]
- 问题链接：https://www.shiyanlou.com/questions/169080
- 学员昵称：有梦想是好事
- 提问时间：2019-06-05T08:38:31.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid971600-20190605-1559723868662)

老师，能否给出此偏导的求解过程，自己试了几次都不知道怎么去求，感谢。

**Comment by songyer** [comment]
已回答
