### ISSUE TITLE
请问为什么会等于矩阵y-aw的转置呢

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#136]
- 问题链接：https://www.shiyanlou.com/questions/169796
- 学员昵称：fang151liu
- 提问时间：2019-06-11T02:25:23.000Z

---

![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid387372-20190611-1560219878230)

**Comment by songyer** [comment]
已回答
