### ISSUE TITLE
使用GAN生成漫画人物头像-挑战知识点有误

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#35]
- 问题链接：https://www.shiyanlou.com/questions/88285
- 学员昵称：被秒的BOSS
- 提问时间：2018-10-29T14:19:34.000Z

**Comment by daihuidai** [comment]
挑战知识点有误应该为：
PyTorch运用
深度卷积生成对抗网络

**Comment by huhuhang** [comment]
已修改
