### ISSUE TITLE
分类监督学习的思维导图里拼写错误

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#56]
- 问题链接：https://www.shiyanlou.com/questions/88768
- 学员昵称：被秒的BOSS
- 提问时间：2018-11-03T02:30:17.000Z

**Comment by daihuidai** [comment]
实验十四 袋装和提升 思维导图的sigmoid拼写错误

**Comment by huhuhang** [comment]
已修改
