### ISSUE TITLE
决策树实验的男女预测的例子的树的可视化问题

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#81]
- 问题链接：https://www.shiyanlou.com/questions/101962
- 学员昵称：可燃冰
- 提问时间：2019-01-19T06:45:24.000Z

<details>
<summary>问题详情</summary>
如下图所示， 按照代码我生成出的决策树 最深一层thick对应为man，和图上不一致
![图片描述](https://dn-simplecloud.shiyanlou.com/uid/13790/1547880226560.png-wm)

</details>

**Comment by huhuhang** [comment]
@daihuidai 直接修订即可。

**Comment by daihuidai** [comment]
@huhuhang 这里涉及到绘图问题，原来的图片表述有误
