### ISSUE TITLE
请问如何把graphviz的图形导出

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#82]
- 问题链接：https://www.shiyanlou.com/questions/101970
- 学员昵称：可燃冰
- 提问时间：2019-01-19T08:11:29.000Z

<details>
<summary>问题详情</summary>
决策树实验。
由于可视化决策树的图形较大，需要导出图像。
我在网上查看了似乎out_file是指定输出路径的，我试了一下发生报错了，请问是我的用法有问题吗？
![图片描述](https://dn-simplecloud.shiyanlou.com/uid/13790/1547885311562.png-wm)

</details>

**Comment by daihuidai** [comment]
他这种写法肯定是错误的并不是直接输出文件，但是不是很清楚export_graphviz中out_file的用法，我们环境sklearn是0.19，out_file应该可以使用tree.dot，在0.20中才会修改默认值为None。

**Comment by huhuhang** [comment]
既然实验中都可以画出来了，notebook 图片另存为就可以了啊。 @daihuidai

**Comment by daihuidai** [comment]
@huhuhang 是可以直接保存图片，但是out_file参数并没有功能介绍，该提问者指定该参数时出错，可能需要给他一个错误的原因。
