### ISSUE TITLE
数学计算过程

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#98]
- 问题链接：https://www.shiyanlou.com/questions/108327
- 学员昵称：书山压力大EE
- 提问时间：2019-04-24T13:03:36.000Z

---

$$
f = \sum\limits_{i = 1}^n {{{(y_{i}-(w_0 + w_1x_{i}))}}^2} \tag{5}
$$

$$
\frac{\partial f}{\partial w_{1}}=-2(\sum_{i=1}^{n}{x_iy_i}-w_{0}\sum_{i=1}^{n}{x_i}-w_{1}\sum_{i=1}^{n}{x_i}^2) \tag{6b}
$$

这个偏导的数学求解过程   ,  能不能详细的给一下，   我计算出来不太一样

**Comment by songyer** [comment]
已回答
