### ISSUE TITLE
对矩阵求偏导的疑问

### ISSUE THREAD

**Issue by huhuhang** [shiyanlou/louplus-ml#99]
- 问题链接：https://www.shiyanlou.com/questions/108342
- 学员昵称：书山压力大EE
- 提问时间：2019-04-24T13:32:28.000Z

---

看到对w矩阵的偏导都作用在 
 $
w^{T}
$上了， 所以想问问清楚：

假如$f =  y^{T}y - 2 X^{T}y + X^{T}(XW)$

这时候$\frac{\partial f}{\partial W}$
结果是多少？

**Comment by songyer** [comment]
已回答
